<?php

/**
 * @file
 * Contains api_user.module.
 */
use Drupal\user\Entity\User;

use Drupal\Core\Routing\RouteMatchInterface;
use Drupal\rest\ResourceResponse;

/**
 * Implements hook_help().
 */
function api_user_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the api_user module.
    case 'help.page.api_user':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Endpoints for User auth') . '</p>';
      return $output;

    default:
  }
}

function api_user_preprocess_page(&$vars)
{
  \Drupal::logger('api_user')->warning('DEBUGGING CURRENT USER ID: ' . \Drupal::currentUser()->id());

}


function api_user_file_download($uri) {

  /** @var User $user */
  $user = User::load(\Drupal::currentUser()->id());
  $roles = $user->getRoles();
  if (!sin_array('administrator', $roles)) {
    return -1;
  }

}
