name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.1
          version: 1
          command: install
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete
          remote_path: /var/www/html/
          remote_user: ${{ secrets.USER }}
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.KEY }}
