name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite
          coverage: none
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install Composer dependencies
        run: composer install --prefer-dist --no-interaction --no-suggest
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude /web/sites/*/settings.local.php --exclude /web/sites/*/files/ --exclude linux_amd64_DirectQueueGo
          remote_path: /var/www/api.moweb.info
          remote_user: ${{ secrets.USER }}
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.KEY }}


