name: PHP Composer

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          path: main
      - name: Install Composer dependencies
        uses: php-actions/composer@v5
        with:
          php_version: 7.3
          version: 1
          command: composer install --prefer-dist --no-interaction --no-suggest
      - name: rsync deployments
        uses: burnett01/rsync-deployments@4.1
        with:
          switches: -avzr --delete --exclude /web/sites/*/settings.local.php --exclude /web/sites/*/files/ --exclude linux_amd64_DirectQueueGo
          remote_path: ${{ secrets.PATH }}
          remote_user: ${{ secrets.USER }}
          remote_host: ${{ secrets.HOST }}
          remote_key: ${{ secrets.KEY }}


